// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXsi6usWtBRZWgvJr3qDjlwjWAiCtVcVU',
    appId: '1:961090658797:web:258861ebc607be400f07e4',
    messagingSenderId: '961090658797',
    projectId: 'whatsapp-8fbbf',
    authDomain: 'whatsapp-8fbbf.firebaseapp.com',
    storageBucket: 'whatsapp-8fbbf.appspot.com',
    measurementId: 'G-7TG26D5BZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OtoQ1oSUrKfcfGYJgETS6o92Ah0xOl0',
    appId: '1:961090658797:android:157b9a36247f5bec0f07e4',
    messagingSenderId: '961090658797',
    projectId: 'whatsapp-8fbbf',
    storageBucket: 'whatsapp-8fbbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkFHads7pV64RKliu54Aml0BMXCUU2LI0',
    appId: '1:961090658797:ios:9f6baa25fee0c8850f07e4',
    messagingSenderId: '961090658797',
    projectId: 'whatsapp-8fbbf',
    storageBucket: 'whatsapp-8fbbf.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkFHads7pV64RKliu54Aml0BMXCUU2LI0',
    appId: '1:961090658797:ios:9f6baa25fee0c8850f07e4',
    messagingSenderId: '961090658797',
    projectId: 'whatsapp-8fbbf',
    storageBucket: 'whatsapp-8fbbf.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXsi6usWtBRZWgvJr3qDjlwjWAiCtVcVU',
    appId: '1:961090658797:web:0caab601f69c560c0f07e4',
    messagingSenderId: '961090658797',
    projectId: 'whatsapp-8fbbf',
    authDomain: 'whatsapp-8fbbf.firebaseapp.com',
    storageBucket: 'whatsapp-8fbbf.appspot.com',
    measurementId: 'G-CD615R8CRM',
  );
}
